### ISSUE TITLE
High quality pen is blurry

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-render#1]
### Expected Behavior

When high quality pen is enabled, pen lines should always look smooth.

### Actual Behavior

The edges of pen lines become overly blurry when stage is zoomed in.

**Comment by Dieforrobux** [comment]
> ### Expected Behavior
> When high quality pen is enabled, pen lines should always look smooth.
> 
> ### Actual Behavior
> The edges of pen lines become overly blurry when stage is zoomed in.

Well. I always use i high quailty pen, Because if its pen. I like it better. I zoom it with fullscreen/*using finger/mouse* and scrolling. Using up&down scrolling (going backwords/going behind). Also (only way) making my finger/mouse up&down (but they start coming to each other they start scrolling out.)

**Comment by raymonable** [comment]
I'm sure this is already known by you at this point, but the canvas still has a built-in resolution. It's very difficult to make it not look "blurry" zoomed in unless pen is chosen to be re-implemented as SVG (in which it'd be as scalable as you want) but performance would take a very large hit.

If you're OK with sharp edges (instead of blurry), you can add 
```css
canvas {
    image-rendering: pixelated;
}
```
and it will appear sharp.
